### ISSUE TITLE
Dropdown window too small

### ISSUE THREAD

**Issue by JohnHSydney** [Le0Michine/worldtime-extension#1]
Greetings: This is a good add-on, although not quite as clean and easy as Foxclocks, which is not compatible with Firefox 57. One small point: when the dropdown is activated, it is not quite wide enough for the data and therefore a slider appears at its base (see screen grab)
![screen shot 11-12-17 at 10 06 am](https://user-images.githubusercontent.com/33584778/32694330-43a17b30-c791-11e7-95e9-ded3fc27f3da.PNG)
.
There is only a small amount of data left to display, so it's annoying to need to go up to the window and move the slider a little to the right.
Please make the initial dropdown a little wider, if possible. Thanks.

**Comment by Le0Michine** [comment]
@JohnHSydney thanks for reporting, will check it out soon
